/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface WAppear {
    'alpha': number;
  }
  interface WAppearAttributes extends StencilHTMLAttributes {
    'alpha'?: number;
  }

  interface WDelay {
    'frames': number;
    'speed': number;
  }
  interface WDelayAttributes extends StencilHTMLAttributes {
    'frames'?: number;
    'speed'?: number;
  }

  interface WSetup {}
  interface WSetupAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'WAppear': Components.WAppear;
    'WDelay': Components.WDelay;
    'WSetup': Components.WSetup;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'w-appear': Components.WAppearAttributes;
    'w-delay': Components.WDelayAttributes;
    'w-setup': Components.WSetupAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLWAppearElement extends Components.WAppear, HTMLStencilElement {}
  var HTMLWAppearElement: {
    prototype: HTMLWAppearElement;
    new (): HTMLWAppearElement;
  };

  interface HTMLWDelayElement extends Components.WDelay, HTMLStencilElement {}
  var HTMLWDelayElement: {
    prototype: HTMLWDelayElement;
    new (): HTMLWDelayElement;
  };

  interface HTMLWSetupElement extends Components.WSetup, HTMLStencilElement {}
  var HTMLWSetupElement: {
    prototype: HTMLWSetupElement;
    new (): HTMLWSetupElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'w-appear': HTMLWAppearElement
    'w-delay': HTMLWDelayElement
    'w-setup': HTMLWSetupElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'w-appear': HTMLWAppearElement;
    'w-delay': HTMLWDelayElement;
    'w-setup': HTMLWSetupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
